#Peterson Wiggers
### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar todos Sem Id e Valor
GET http://localhost:8000/produtoSemId_Valor/ HTTP/1.1
### Verbo GET – listar um
GET http://localhost:8000/produto/1 HTTP/1.1
### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
Content-Type: application/json

{
  "nome": "Camiseta Básica 5",
  "descricao": "Camiseta de algodão manga curta",
  "foto": "iVBORw0KGgoAAAANSUhEUgAA...",
  "valor_unitario": 49.90
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/1 HTTP/1.1
Content-Type: application/json

{
  "nome": "Camiseta Básica 10",
  "descricao": "Camiseta de algodão",
  "foto": "aGVsbG8gd29ybGQ=",
  "valor_unitario": 49.90
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/1 HTTP/1.1