#Peterson Wiggers
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMTExMTExMTExMSIsImlkIjoyLCJncnVwbyI6MSwiZXhwIjoxNzc0NzMzODY2LCJ0eXBlIjoiYWNjZXNzIn0.3L3LwnWzYSHEJ-Ipnh4U4clc_Th6RqL3WqdxL_5BDLY

### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1
Authorization: Bearer {{access_token}}
### Verbo GET – listar um
GET http://localhost:8000/cliente/1 HTTP/1.1
Authorization: Bearer {{access_token}}
### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Ana Souza",
  "cpf": "12345678901",
  "telefone": "49999887766"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Ana Souza 2",
  "cpf": "12345678901",
  "telefone": "49999887766"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1