#Peterson Wiggers
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWQiOjEsImdydXBvIjoxLCJleHAiOjE3NzYwMTQwMjUsInR5cGUiOiJhY2Nlc3MifQ.5YyrO3bnvJf42fHD_XzoeMHxQ1sDFSkhzHPi-k0KTBU
### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{access_token}}
### Verbo GET – listar um
GET http://localhost:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{access_token}}
### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Peterson Wiggers",
  "matricula": "MAT2026001",
  "cpf": "00000000000",
  "telefone": "49999998888",
  "grupo": 2,
  "senha": "senha123"
}

### POST – adicionar Deja Wiggers
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Deja Wiggers",
  "matricula": "MAT2026001",
  "cpf": "11111111111",
  "telefone": "49999998888",
  "grupo": 1,
  "senha": "senha123"
}

### POST – adicionar Alisson Wiggers
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Alisson Wiggers",
  "matricula": "MAT2026001",
  "cpf": "22222222222",
  "telefone": "49999998888",
  "grupo": 2,
  "senha": "senha123"
}

### POST – adicionar Fernanda Bergmeier
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Fernanda Bergmeier",
  "matricula": "MAT2026001",
  "cpf": "33333333333",
  "telefone": "49999998888",
  "grupo": 3,
  "senha": "senha123"
}

### POST – adicionar Fernanda Bergmeier
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Zé das Batatas",
  "matricula": "MAT2026001",
  "cpf": "11111111111",
  "telefone": "49999998888",
  "grupo": 3,
  "senha": "senha123"
}


### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "nome": "Larissa Bergmeier",
  "matricula": "MAT2001",
  "cpf": "12548",
  "telefone": "49999998888",
  "grupo": 3,
  "senha": "senha123"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1
Authorization: Bearer {{access_token}}